export const keys = {
  GET_DROP_BOX: 'DROP_BOX',
  GET_MAIN_BOARD: 'MAIN_BOARD',
  GET_SORT_MAIN_BOARD: 'GET_SORT_MAIN_BOARD',
  POST_SIGNUP: 'SIGNUP',
  POST_EMAIL_COMFIRM: 'EMAIL_COMFIRM',
  POST_BOARDS: 'BOARDS',
  PUT_LIKE: 'ISLIKE',
  GET_DETAIL_BOARD: 'DETAIL_BOARD',
  GET_COMMENT: 'COMMENT',
  POST_ADD_COMMENT: 'ADD_COMMENT',
  POST_DELETE_COMMENT: 'DELETE_COMMENT',
  POST_PATTH_COMMENT: 'PATTH_COMMENT',
};
