export const keys = {
  GET_DROP_BOX: 'DROP_BOX',
  GET_MAIN_BOARD: 'MAIN_BOARD',
  POST_SIGNUP: 'SIGNUP',
  POST_EMAIL_COMFIRM: 'EMAIL_COMFIRM',
  POST_BOARDS: 'BOARDS',
  PUT_LIKE: 'ISLIKE',
  GET_DETAIL_BOARD: 'DETAIL_BOARD',
};
